name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  geolocator: ^10.0.1
  geocoding: ^2.1.0


  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  provider: ^6.1.1
  url_launcher: ^6.0.10
  go_router: ^13.0.0 
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/stadium_marker.png
