// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8wsZcDps0Un_9RR9DSoJMU7alndsznsU',
    appId: '1:489851484529:web:0c814eb2d17f8008e8ded0',
    messagingSenderId: '489851484529',
    projectId: 'championship-project-aitu',
    authDomain: 'championship-project-aitu.firebaseapp.com',
    storageBucket: 'championship-project-aitu.firebasestorage.app',
    measurementId: 'G-G343XCLX4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hzVo5Vdy2qHUBQjzz1K6NWt7Kqm5848',
    appId: '1:489851484529:android:da12bedff578506ce8ded0',
    messagingSenderId: '489851484529',
    projectId: 'championship-project-aitu',
    storageBucket: 'championship-project-aitu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdN2sD7VbAoBGWfHoG-gLcTwC5vpcjfY',
    appId: '1:489851484529:ios:e9da55985a9ab618e8ded0',
    messagingSenderId: '489851484529',
    projectId: 'championship-project-aitu',
    storageBucket: 'championship-project-aitu.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdN2sD7VbAoBGWfHoG-gLcTwC5vpcjfY',
    appId: '1:489851484529:ios:e9da55985a9ab618e8ded0',
    messagingSenderId: '489851484529',
    projectId: 'championship-project-aitu',
    storageBucket: 'championship-project-aitu.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8wsZcDps0Un_9RR9DSoJMU7alndsznsU',
    appId: '1:489851484529:web:0a3cb132fc886fe0e8ded0',
    messagingSenderId: '489851484529',
    projectId: 'championship-project-aitu',
    authDomain: 'championship-project-aitu.firebaseapp.com',
    storageBucket: 'championship-project-aitu.firebasestorage.app',
    measurementId: 'G-ME90T5VW1Z',
  );
}
